In [268]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.tsa.api import VAR

In [269]:
raw_spot = pd.read_excel("mf821+project+data.xlsx",sheet_name=0)
raw_future = pd.read_excel("mf821+project+data.xlsx",sheet_name=1)

In [270]:
names = raw_spot.columns

In [307]:
spot_price = [names[x] for x in range(len(names)) if x % 7 == 1]
spot_bid = [names[x] for x in range(len(names)) if x % 7 == 3]
spot_ask = [names[x] for x in range(len(names)) if x % 7 == 5]

price_date = [names[x] for x in range(len(names)) if x % 7 == 0]
bid_date = [names[x] for x in range(len(names)) if x % 7 == 2]
ask_date = [names[x] for x in range(len(names)) if x % 7 == 4]

In [308]:
raw_bid_prices = raw_spot[spot_bid]
raw_ask_prices = raw_spot[spot_ask]
raw_prices = raw_spot[spot_price]

In [309]:
bid_dates = raw_spot[bid_date]
ask_dates = raw_spot[ask_date]
price_dates = raw_spot[price_date]

In [310]:
col_bid = raw_bid_prices.columns
col_bid = col_bid[::-1]

col_ask = raw_ask_prices.columns
col_ask = col_ask[::-1]

col_price = raw_prices.columns
col_price = col_price[::-1]

In [311]:
col_bid_date = bid_dates.columns
col_bid_date = col_bid_date[::-1]

col_ask_date = ask_dates.columns
col_ask_date = col_ask_date[::-1]

col_price_date = price_dates.columns
col_price_date = col_price_date[::-1]

In [312]:
all_bids = pd.concat([ raw_bid_prices[col_bid[i]].dropna() for i in range(len(col_bid))])#.isna().sum()#.dropna()
all_asks = pd.concat([ raw_ask_prices[col_ask[i]].dropna() for i in range(len(col_ask))])
all_prices = pd.concat([ raw_prices[col_price[i]].dropna() for i in range(len(col_price))])

In [313]:
all_bid_dates = pd.concat([ bid_dates[col_bid_date[i]].dropna() for i in range(len(col_bid_date))])
all_ask_dates = pd.concat([ ask_dates[col_ask_date[i]].dropna() for i in range(len(col_ask_date))])
all_price_dates = pd.concat([ price_dates[col_price_date[i]].dropna() for i in range(len(col_price_date))])

In [314]:
p = pd.to_datetime(all_bid_dates)
agg = pd.DataFrame([all_bids.values, all_asks.values, all_prices.values]).T

In [315]:
agg.columns = ["Bid", "Ask", "Price"]
agg["Mid"] = (agg["Bid"] + agg["Ask"]) / 2
agg = agg.set_index(p)
#agg

In [316]:
agg_spot = agg.resample('1T').first().fillna(method="bfill")
#agg_spot

In [317]:
names = raw_future.columns

future_price = [names[x] for x in range(len(names)) if x % 7 == 1]
future_bid = [names[x] for x in range(len(names)) if x % 7 == 3]
future_ask = [names[x] for x in range(len(names)) if x % 7 == 5]

price_date = [names[x] for x in range(len(names)) if x % 7 == 0]
bid_date = [names[x] for x in range(len(names)) if x % 7 == 2]
ask_date = [names[x] for x in range(len(names)) if x % 7 == 4]

raw_bid_prices = raw_future[future_bid]
raw_ask_prices = raw_future[future_ask]
raw_prices = raw_future[future_price]

bid_dates = raw_future[bid_date]
ask_dates = raw_future[ask_date]
price_dates = raw_future[price_date]

col_bid = raw_bid_prices.columns
col_bid = col_bid[::-1]

col_ask = raw_ask_prices.columns
col_ask = col_ask[::-1]

col_price = raw_prices.columns
col_price = col_price[::-1]

col_bid_date = bid_dates.columns
col_bid_date = col_bid_date[::-1]

col_ask_date = ask_dates.columns
col_ask_date = col_ask_date[::-1]

col_price_date = price_dates.columns
col_price_date = col_price_date[::-1]

all_bids = pd.concat([ raw_bid_prices[col_bid[i]].dropna() for i in range(len(col_bid))])#.isna().sum()#.dropna()
all_asks = pd.concat([ raw_ask_prices[col_ask[i]].dropna() for i in range(len(col_ask))])
all_prices = pd.concat([ raw_prices[col_price[i]].dropna() for i in range(len(col_price))])

all_bid_dates = pd.concat([ bid_dates[col_bid_date[i]].dropna() for i in range(len(col_bid_date))])
all_ask_dates = pd.concat([ ask_dates[col_ask_date[i]].dropna() for i in range(len(col_ask_date))])
all_price_dates = pd.concat([ price_dates[col_price_date[i]].dropna() for i in range(len(col_price_date))])

p = pd.to_datetime(all_ask_dates)
agg = pd.DataFrame([all_bids.values, all_asks.values, all_prices.values]).T

agg.columns = ["Bid", "Ask", "Price"]
agg["Mid"] = (agg["Bid"] + agg["Ask"]) / 2
agg = agg.set_index(p)
agg_future = agg.resample('1T').first().fillna(method="bfill")
#agg_future

In [321]:
final_df = pd.merge(agg_spot, agg_future, how="outer", left_index=True, right_index=True).dropna()
final_df.columns = ["Spot_bid", "Spot_ask", "Spot_price", "Spot_mid", "Future_bid", "Future_ask", "Future_price", "Future_mid"]
final_df

,Spot_bid,Spot_ask,Spot_price,Spot_mid,Future_bid,Future_ask,Future_price,Future_mid
2017-11-22 20:00:00,1084.9,1087.6,1086.25,1086.25,1086.2,1086.4,1086.2,1086.70
2017-11-22 20:01:00,1086.5,1086.8,1086.65,1086.65,1086.2,1086.6,1086.2,1086.70
2017-11-22 20:02:00,1086.6,1086.9,1086.75,1086.75,1086.2,1086.9,1086.2,1086.70
2017-11-22 20:03:00,1086.5,1086.7,1086.60,1086.60,1086.2,1086.9,1086.2,1086.70
2017-11-22 20:04:00,1086.8,1087.0,1086.90,1086.90,1086.2,1086.9,1086.2,1086.70
2017-11-22 20:05:00,1086.9,1087.1,1087.00,1087.00,1086.2,1087.2,1086.2,1086.70
2017-11-22 20:06:00,1087.0,1087.1,1087.05,1087.05,1086.2,1087.2,1086.2,1086.70
2017-11-22 20:07:00,1087.1,1087.3,1087.20,1087.20,1086.2,1087.3,1086.2,1086.70
2017-11-22 20:08:00,1087.2,1087.5,1087.35,1087.35,1086.2,1087.6,1086.2,1086.70
2017-11-22 20:09:00,1087.7,1088.0,1087.85,1087.85,1086.2,1087.6,1086.2,1086.70
2017-11-22 20:10:00,1087.7,1088.0,1087.85,1087.85,1086.2,1087.8,1086.2,1086.70
2017-11-22 20:11:00,1087.8,1088.0,1087.90,1087.90,1086.2,1087.1,1086.2,1086.70
2017-11-22 20:12:00,1087.2,1087.5,1087.35,1087.35,1086.2,1087.1,1086.2,1086.70
2017-11-22 20:13:00,1087.1,1087.3,1087.20,1087.20,1086.2,1087.3,1086.2,1086.70
2017-11-22 20:14:00,1087.2,1087.5,1087.35,1087.35,1086.2,1087.0,1086.2,1086.70
2017-11-22 20:15:00,1087.3,1087.5,1087.40,1087.40,1086.2,1087.0,1086.2,1086.70
2017-11-22 20:16:00,1087.1,1087.3,1087.20,1087.20,1086.2,1087.2,1086.2,1086.70
2017-11-22 20:17:00,1087.2,1087.5,1087.35,1087.35,1086.2,1087.0,1086.2,1086.70
2017-11-22 20:18:00,1087.1,1087.4,1087.25,1087.25,1086.2,1087.0,1086.2,1086.70
2017-11-22 20:19:00,1087.1,1087.3,1087.20,1087.20,1086.2,1087.1,1086.2,1086.70
2017-11-22 20:20:00,1087.0,1087.4,1087.20,1087.20,1086.2,1087.1,1086.2,1086.70
2017-11-22 20:21:00,1087.0,1087.4,1087.20,1087.20,1086.2,1087.1,1086.2,1086.70
2017-11-22 20:22:00,1087.2,1087.5,1087.35,1087.35,1086.2,1087.3,1086.2,1086.70
2017-11-22 20:23:00,1087.4,1087.5,1087.45,1087.45,1086.2,1087.1,1086.2,1086.70
2017-11-22 20:24:00,1087.2,1087.4,1087.30,1087.30,1086.2,1087.1,1086.2,1086.70
2017-11-22 20:25:00,1086.9,1087.1,1087.00,1087.00,1086.2,1086.7,1086.2,1086.70
2017-11-22 20:26:00,1086.6,1086.9,1086.75,1086.75,1086.2,1087.1,1086.2,1086.70
2017-11-22 20:27:00,1086.8,1087.0,1086.90,1086.90,1086.2,1087.1,1086.2,1086.70
2017-11-22 20:28:00,1087.0,1087.2,1087.10,1087.10,1086.2,1086.9,1086.2,1086.70
2017-11-22 20:29:00,1086.8,1087.3,1087.05,1087.05,1086.2,1087.3,1086.2,1086.70
...,...,...,...,...,...,...,...,...
2017-12-04 01:00:00,1088.4,1088.6,1088.50,1088.50,1088.5,1088.6,1088.5,1088.55
2017-12-04 01:01:00,1088.5,1088.8,1088.65,1088.65,1088.6,1088.7,1088.7,1088.65
2017-12-04 01:02:00,1088.5,1088.8,1088.65,1088.65,1088.5,1088.6,1088.6,1088.55
2017-12-04 01:03:00,1088.6,1088.9,1088.75,1088.75,1088.5,1088.6,1088.5,1088.55
2017-12-04 01:04:00,1088.5,1088.8,1088.65,1088.65,1088.5,1088.6,1088.5,1088.55
2017-12-04 01:05:00,1088.5,1088.8,1088.65,1088.65,1088.5,1088.6,1088.6,1088.55
2017-12-04 01:06:00,1088.5,1088.7,1088.60,1088.60,1088.7,1088.8,1088.7,1088.75
2017-12-04 01:07:00,1088.6,1088.8,1088.70,1088.70,1088.7,1088.8,1088.8,1088.75
2017-12-04 01:08:00,1088.7,1088.9,1088.80,1088.80,1088.7,1088.8,1088.8,1088.75
2017-12-04 01:09:00,1088.6,1088.9,1088.75,1088.75,1088.7,1088.8,1088.8,1088.75
2017-12-04 01:10:00,1088.7,1089.0,1088.85,1088.85,1088.8,1088.9,1088.8,1088.85
2017-12-04 01:11:00,1088.7,1089.0,1088.85,1088.85,1088.7,1088.8,1088.7,1088.75
2017-12-04 01:12:00,1088.8,1089.0,1088.90,1088.90,1088.7,1088.8,1088.7,1088.75
2017-12-04 01:13:00,1088.6,1089.0,1088.80,1088.80,1088.7,1088.8,1088.8,1088.75
2017-12-04 01:14:00,1088.7,1089.0,1088.85,1088.85,1088.7,1088.8,1088.7,1088.75
2017-12-04 01:15:00,1088.7,1089.0,1088.85,1088.85,1088.7,1088.8,1088.8,1088.75
2017-12-04 01:16:00,1088.7,1089.0,1088.85,1088.85,1088.7,1088.8,1088.8,1088.75
2017-12-04 01:17:00,1088.9,1089.1,1089.00,1089.00,1088.9,1089.0,1088.9,1088.95
2017-12-04 01:18:00,1088.8,1089.1,1088.95,1088.95,1089.4,1089.6,1089.5,1089.50
2017-12-04 01:19:00,1089.1,1089.3,1089.20,1089.20,1089.6,1089.7,1089.6,1089.65
2017-12-04 01:20:00,1089.9,1090.1,1090.00,1090.00,1089.6,1089.7,1089.6,1089.65
2017-12-04 01:21:00,1089.5,1090.0,1089.75,1089.75,1089.5,1089.6,1089.6,1089.55
2017-12-04 01:22:00,1089.6,1089.9,1089.75,1089.75,1089.5,1089.6,1089.5,1089.55
2017-12-04 01:23:00,1089.6,1089.9,1089.75,1089.75,1089.3,1089.5,1089.4,1089.40
2017-12-04 01:24:00,1089.5,1089.7,1089.60,1089.60,1089.3,1089.5,1089.4,1089.40
2017-12-04 01:25:00,1089.3,1089.5,1089.40,1089.40,1089.3,1089.4,1089.3,1089.35
2017-12-04 01:26:00,1089.2,1089.5,1089.35,1089.35,1089.2,1089.3,1089.2,1089.25
2017-12-04 01:27:00,1089.1,1089.4,1089.25,1089.25,1088.6,1088.7,1088.7,1088.65
2017-12-04 01:28:00,1089.3,1089.6,1089.45,1089.45,1088.6,1088.7,1088.7,1088.65
2017-12-04 01:29:00,1088.9,1089.1,1089.00,1089.00,1088.5,1088.6,1088.6,1088.55

In [322]:
final_df.index

DatetimeIndex(['2017-11-22 20:00:00', '2017-11-22 20:01:00',
               '2017-11-22 20:02:00', '2017-11-22 20:03:00',
               '2017-11-22 20:04:00', '2017-11-22 20:05:00',
               '2017-11-22 20:06:00', '2017-11-22 20:07:00',
               '2017-11-22 20:08:00', '2017-11-22 20:09:00',
               ...
               '2017-12-04 01:20:00', '2017-12-04 01:21:00',
               '2017-12-04 01:22:00', '2017-12-04 01:23:00',
               '2017-12-04 01:24:00', '2017-12-04 01:25:00',
               '2017-12-04 01:26:00', '2017-12-04 01:27:00',
               '2017-12-04 01:28:00', '2017-12-04 01:29:00'],
              dtype='datetime64[ns]', length=16170, freq='T')

In [330]:
# Index a certain day to feed into VAR
sample = final_df[["Spot_mid", "Future_mid"]]['2017-11-24']

In [331]:
model = VAR(sample)
res = model.fit(1)
res.summary()

  Summary of Regression Results
==================================
Model:                         VAR
Method:                        OLS
Date:           Wed, 01, May, 2019
Time:                     15:57:42
--------------------------------------------------------------------
No. of Equations:         2.00000    BIC:                   -12.1464
Nobs:                     1439.00    HQIC:                  -12.1602
Log likelihood:           4677.47    FPE:                5.19189e-06
AIC:                     -12.1684    Det(Omega_mle):     5.17031e-06
--------------------------------------------------------------------
Results for equation Spot_mid
================================================================================
                   coefficient       std. error           t-stat            prob
--------------------------------------------------------------------------------
const               103.802977        13.133045            7.904           0.000
L1.Spot_mid           0.914169         0.009347           97.803           0.000
L1.Future_mid        -0.009793         0.004835           -2.026           0.043
================================================================================

Results for equation Future_mid
================================================================================
                   coefficient       std. error           t-stat            prob
--------------------------------------------------------------------------------
const                79.839200        17.346567            4.603           0.000
L1.Spot_mid          -0.036187         0.012346           -2.931           0.003
L1.Future_mid         0.962626         0.006386          150.739           0.000
================================================================================

Correlation matrix of residuals
              Spot_mid  Future_mid
Spot_mid      1.000000    0.120625
Future_mid    0.120625    1.000000